# Generated by Django 4.2.3 on 2023-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actorsCommonStarWars',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='producedBefore2015',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='withPaulWalker',
            field=models.BooleanField(default=False),
        ),
    ]
